import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-helvetica">
        {/* Global SVG Gradient Definition */}
        <svg className="svg-gradient-defs">
          <defs>
            <linearGradient
              id="icon-gradient"
              x1="100%"
              y1="0%"
              x2="0%"
              y2="100%"
            >
              <stop offset="0%" stopColor="#FFC31B" />
              <stop offset="25%" stopColor="#C496BD" />
              <stop offset="50%" stopColor="#F66D82" />
              <stop offset="75%" stopColor="#FD6240" />
              <stop offset="100%" stopColor="#CB3D73" />
            </linearGradient>
          </defs>
        </svg>
        {children}
      </body>
    </html>
  );
}
